apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-cluster-deploy-9
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anandambitionv2/appofapps.git
    targetRevision: main
    path: external-cluster-2-deploy-apps
  destination:
    server: https://aks-private-pure-dns-trfujra4.0dc1235a-43f4-461a-a82d-52d64bb02521.privatelink.centralindia.azmk8s.io
    # namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true