apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-cluster-deploy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anandambitionv2/appofapps.git
    targetRevision: main
    path: external-cluster-deploy
  destination:
    server: https://aks-private-dns-wed6ccoz.93d20030-3b00-4387-a693-029b5f8ae794.privatelink.centralindia.azmk8s.io
    # namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true