apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imageupdaterapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anandambitionv2/appofapps.git
    targetRevision: main
    path: imageupdater
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true