apiVersion: v1
kind: Secret
metadata:
  name: private-k8s-cluster-new-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: private-k8s-cluster-new
  server: https://aks-cluster-private-2-dns-f1due4ay.0dd60976-e318-4560-b69d-69b1445876e0.privatelink.centralindia.azmk8s.io
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "env": {
          "AAD_ENVIRONMENT_NAME": "AzurePublicCloud",
          "AZURE_CLIENT_ID": "9b8ebe70-8d9f-4fc5-ae51-33f725c87ca2",
          "AAD_LOGIN_METHOD": "workloadidentity"
        },
        "args": ["azure"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": true
      }
    }