apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-2-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-2-app
  template:
    metadata:
      labels:
        app: external-2-app
    spec:
      

      containers:
      - name: nginx
        image: nginxdemos/hello

        
        