apiVersion: apps/v1
kind: Deployment
metadata:
  name: sap-prod
  namespace: sap-prod-ns
  labels:
    app: sap-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sap-prod
  template:
    metadata:
      labels:
        app: sap-prod
    spec:
      containers:
      - name: sap-prod
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80