apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-mysecretkv-spc # needs to be unique per namespace
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "74f29324-d303-4ac7-b00a-b319f6c7d4dd" # Setting this to use workload identity
    keyvaultName: aks-kv-112     # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: vaulted           # Set to the name of your secret
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        
    tenantId: 5f8d3f88-8e5b-4e25-9d00-e62229c9cc71     # The tenant ID of the key vault