apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-backend
  namespace: default
  labels:
    app: student-backend
spec:
  replicas: 2
  
  selector:
    matchLabels:
      app: student-backend
  template:
    metadata:
      labels:
        app: student-backend
    spec:
      serviceAccountName: kv-sa
      containers:
      - name: student1
        image: acrwinter.azurecr.io/backend:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: secrets-store-1
          mountPath: "/mnt/secrets-store"
          readOnly: true

        env:
        # - name: DB_SERVER
        #   value: sqlforstudents.database.windows.net

        # - name: DB_NAME
        #   value: SchoolDB

        - name: AZURE_CLIENT_ID
          value: 920cc0de-b967-4a50-958c-8a9d0fa2aedc
        - name: AZURE_CLIENT_SECRET
          value: test

        # - name: DB_PASSWORD
        #   value: Atlanta@44

      volumes:
        - name: secrets-store-1
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-mysecretkv-spc