
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-sap-prod-app
  namespace: sap-prod-ns
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-sap-prod-app
  template:
    metadata:
      labels:
        app: rollout-sap-prod-app
    spec:
      containers:
      - name: rollouts-demo
        image: acrargotest.azurecr.io/frontend
        imagePullPolicy: Always
      
  strategy:
    blueGreen: 
      # activeService specifies the service to update with the new template hash at time of promotion.
      # This field is mandatory for the blueGreen update strategy.
      activeService: rollout-sap-prod-app-active
      # previewService specifies the service to update with the new template hash before promotion.
      # This allows the preview stack to be reachable without serving production traffic.
      # This field is optional.
      previewService: rollout-sap-prod-app-preview
      # autoPromotionEnabled disables automated promotion of the new stack by pausing the rollout
      # immediately before the promotion. If omitted, the default behavior is to promote the new
      # stack as soon as the ReplicaSet are completely ready/available.
      # Rollouts can be resumed using: `kubectl argo rollouts promote ROLLOUT`
      autoPromotionEnabled: false

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-sap-prod-app-active
  namespace: sap-prod-ns

spec:
  type: LoadBalancer
  selector:
    app: rollout-sap-prod-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
kind: Service

apiVersion: v1
metadata:
  name: rollout-sap-prod-app-preview
  namespace: sap-prod-ns
spec:
  type: LoadBalancer
  selector:
    app: rollout-sap-prod-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80